README.md

Change req to Java 1.6

---

build.gradle

See: https://code.google.com/p/google-gson/issues/detail?id=588
PTAL @broady

:wrench: Updated GSON dep to working version

---

src/main/java/com/google/maps/DirectionsApi.java
src/main/java/com/google/maps/DirectionsApiRequest.java
src/main/java/com/google/maps/DistanceMatrixApi.java
src/main/java/com/google/maps/DistanceMatrixApiRequest.java
src/main/java/com/google/maps/ElevationApi.java
src/main/java/com/google/maps/GeoApiContext.java
src/main/java/com/google/maps/GeocodingApiRequest.java
src/main/java/com/google/maps/PendingResultBase.java
src/main/java/com/google/maps/TimeZoneApi.java
src/main/java/com/google/maps/internal/ApiConfig.java
src/test/java/com/google/maps/DistanceMatrixApiTest.java
src/test/java/com/google/maps/ElevationApiTest.java
src/test/java/com/google/maps/GeoApiContextTest.java

Added ApiConfig for more configurable API endpoints

---

src/test/java/com/google/maps/GeocodingApiTest.java

Fixed broken test caused by API data

---

src/main/java/com/google/maps/DirectionsApiRequest.java
src/main/java/com/google/maps/DistanceMatrixApiRequest.java
src/main/java/com/google/maps/internal/FareAdapter.java
src/main/java/com/google/maps/internal/OkHttpPendingResult.java
src/main/java/com/google/maps/model/DirectionsRoute.java
src/main/java/com/google/maps/model/DistanceMatrixElement.java
src/main/java/com/google/maps/model/Fare.java
src/main/java/com/google/maps/model/TransitMode.java
src/main/java/com/google/maps/model/TransitRoutingPreference.java
src/test/java/com/google/maps/DirectionsApiTest.java
src/test/java/com/google/maps/DistanceMatrixApiIntegrationTest.java
src/test/java/com/google/maps/DistanceMatrixApiTest.java

Part of #59. PTAL @domesticmouse @broady 
There's more to come.

Transit Fares in Directions & DistanceMatrix

---

src/test/java/com/google/maps/DirectionsApiTest.java

Fixed broken tests

---

src/main/java/com/google/maps/internal/PolylineEncoding.java

Fixed up polyline doc

---

src/main/java/com/google/maps/GeocodingApiRequest.java
src/main/java/com/google/maps/model/GeocodingResult.java
src/test/java/com/google/maps/GeocodingApiTest.java

Added place ID support to geocoding

---

README.md

Revert support level to Java 7

---

.travis.yml

The 'matrix' rule will run the tests for each item in the list. Global pumps the specified variables into every execution, of which there is now one.

Updated build rules to execute M4W + keyed reqs together

---

src/main/java/com/google/maps/model/Vehicle.java

Fixes vehicle type field name

---

src/main/java/com/google/maps/model/AddressComponentType.java

Added postal_code_prefix (Closes #48)

---

src/main/java/com/google/maps/model/AddressComponentType.java
src/main/java/com/google/maps/model/AddressType.java

This is a fix for https://github.com/googlemaps/google-maps-services-java/issues/94
PTAL @markmcd

Adding Subway Station

---

src/test/java/com/google/maps/PlacesApiIntegrationTest.java

Fixes broken test, as well as fixing the expected/actual order in testPlaceDetailsLookupGoogleSydney()
PTAL @domesticmouse

Places API test fixes

---

src/main/java/com/google/maps/GeoApiContext.java
src/test/java/com/google/maps/ElevationApiIntegrationTest.java
src/test/java/com/google/maps/GeocodingApiTest.java

Tidyup tests + better javadoc.

---

.travis.yml

Working around https://github.com/travis-ci/travis-ci/issues/5227
PTAL @markmcd

Making Travis compile again.

---

src/test/java/com/google/maps/DirectionsApiTest.java
src/test/java/com/google/maps/DistanceMatrixApiIntegrationTest.java

Making the fares tests pass.

---

src/test/java/com/google/maps/DirectionsApiTest.java
src/test/java/com/google/maps/DistanceMatrixApiIntegrationTest.java

Fixing analytics.

---

build.gradle

Upgrade OkHttp

---

build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
src/test/java/com/google/maps/DirectionsApiTest.java

Cleanup for broken test, and marking App Engine dependency as a compile only dependency.

Break fixes

---

src/main/java/com/google/maps/NearbySearchRequest.java
src/test/java/com/google/maps/PlacesApiTest.java

Add support for multiple type for PlacesApi

---

src/main/java/com/google/maps/model/AddressType.java

Add Light Rail Station to AddressType

---

src/main/java/com/google/maps/GaeRequestHandler.java
src/main/java/com/google/maps/OkHttpRequestHandler.java

Fixing merge break caused by https://github.com/googlemaps/google-maps-services-java/pull/186

Fixing up broken merge

---

src/main/java/com/google/maps/DirectionsApiRequest.java
src/test/java/com/google/maps/DirectionsApiTest.java

Fixes https://github.com/googlemaps/google-maps-services-java/issues/203

Save waypoints

---

build.gradle

README already states Java 1.7 as requirement

Update build.gradle to require 1.7

---

build.gradle
src/main/java/com/google/maps/GaeRequestHandler.java
src/main/java/com/google/maps/GeoApiContext.java
src/main/java/com/google/maps/OkHttpRequestHandler.java
src/main/java/com/google/maps/internal/RateLimitExecutorService.java
src/test/java/com/google/maps/GeoApiContextTest.java
src/test/java/com/google/maps/internal/RateLimitExecutorServiceTest.java
src/test/java/com/google/maps/model/EnumsTest.java

PTAL @markmcd 
This is a fix for #261

Replacing hand rolled rate limiter with Gauva's Rate Limiter.

---

src/main/java/com/google/maps/model/AddressComponentType.java
src/main/java/com/google/maps/model/AddressType.java
src/test/java/com/google/maps/GeocodingApiTest.java

Adding undocumented address types.

---

src/main/java/com/google/maps/internal/EncodedPolylineInstanceCreator.java

Adding license declaration for @ArielY15

Fixing license declaration

---

src/main/java/com/google/maps/RoadsApi.java
src/main/java/com/google/maps/model/AddressType.java
src/main/java/com/google/maps/model/AutocompletePrediction.java

Fix for https://github.com/googlemaps/google-maps-services-java/issues/313
@markmcd do you know what this sentence was supposed to be?

Dropping truncated JavaDoc

---

src/main/java/com/google/maps/model/LatLng.java

Fix for https://github.com/googlemaps/google-maps-services-java/issues/303

LatLng serialisation constructor.

---

README.md

Documenting GAE usage

---

README.md

From discussion in https://github.com/googlemaps/google-maps-services-java/issues/338

Add note about paging delay

---

README.md

Update Javadoc link for v0.2.4

---

gradle.properties

Now that 0.2.4 is out, can we open up 0.2.5 development? ;)

Opening up v0.2.5 development

---

src/main/java/com/google/maps/model/AddressType.java

AddressType: add STADIUM

---

src/main/java/com/google/maps/DirectionsApiRequest.java

Reverts googlemaps/google-maps-services-java#393
Change not under CLA

Revert "Made the constructor public"

---

README.md
src/main/java/com/google/maps/GeoApiContext.java
src/main/java/com/google/maps/internal/RateLimitExecutorService.java

Increase default QPS from 10 to 50

---

src/main/java/com/google/maps/model/AddressType.java

Fixing a build breakage.
Ref: https://travis-ci.org/googlemaps/google-maps-services-java/builds/346586611

gradlew googleJavaFormat

---

src/main/java/com/google/maps/model/LatLng.java

Fix for https://github.com/googlemaps/google-maps-services-java/issues/360

Fix for #360

---

src/main/java/com/google/maps/model/AddressType.java

Fix issues:
#426 
#425 
and add more types.

Add new types to AddressType enum.

---

src/main/java/com/google/maps/model/EncodedPolyline.java

adding a default no-arg constructor to EncodedPolyline

---

src/main/java/com/google/maps/model/EncodedPolyline.java

Issue #539. Just fixing Google formatting.

Fixing Google Java Style

---

src/main/java/com/google/maps/model/AutocompletePrediction.java

Add implementation of Serializable to AutocompletePrediction

---

src/main/java/com/google/maps/model/AutocompletePrediction.java

Add Serializable definition to AutoCompletePrediction$Term class

---

CONTRIBUTORS
src/main/java/com/google/maps/PlacesApi.java
src/test/java/com/google/maps/PlacesApiTest.java

Added an overloaded method to enable query and location parameters

---

src/main/java/com/google/maps/PlaceDetailsRequest.java
src/main/java/com/google/maps/model/PlaceDetails.java
src/test/java/com/google/maps/PlacesApiTest.java

Hi Google Maps!
In the spirit of this PR (https://github.com/googlemaps/google-maps-services-java/pull/571) I wanted to contribute userRatingsTotal feature to PlaceDetails request.
My team is currently working on a Google Maps library project that requires this field so it would be great to get it in!
Thanks 🎉

Add userRatingsTotal to PlaceDetails response

---

build.gradle
src/main/java/com/google/maps/PlacesApi.java
src/test/java/com/google/maps/PlacesApiTest.java

- Upgrades to maven-publish plugin for releasing to maven
- Fixes Google file format error that was breaking build

Upgrades release process and fixes file format error

---

src/main/java/com/google/maps/model/AddressType.java
src/test/java/com/google/maps/model/EnumsTest.java

Hey,
Saw our system was failing with this new address type. So I created a PR for it. While waiting for the release, we're running off the forked version.
Thanks,
Vu

Add tourist_attraction address type

---

README.md

Update README to link to our Android Maps and Places SDKs documentation pages.

docs: Updating README to link to Maps/Places SDKs.

---

src/main/java/com/google/maps/GaeRequestHandler.java
src/main/java/com/google/maps/GeoApiContext.java
src/main/java/com/google/maps/OkHttpRequestHandler.java
src/main/java/com/google/maps/internal/HttpHeaders.java
src/main/java/com/google/maps/internal/OkHttpPendingResult.java
src/test/java/com/google/maps/GeoApiContextTest.java

feat: add support for experience id.

---

src/main/java/com/google/maps/model/AddressType.java
src/test/java/com/google/maps/model/EnumsTest.java

fix: missing enum type town square

---

src/main/java/com/google/maps/model/AddressType.java
src/test/java/com/google/maps/model/EnumsTest.java

Add secondary_school and drugstore as AdressType to silence SafeEnumAdapter warnings

---

src/main/java/com/google/maps/DistanceMatrixApi.java

docs: update note about distance matrix

---

src/main/java/com/google/maps/FindPlaceFromTextRequest.java
src/main/java/com/google/maps/PlaceDetailsRequest.java
src/main/java/com/google/maps/model/PlaceDetails.java
src/main/java/com/google/maps/model/PlacesSearchResult.java
src/test/java/com/google/maps/PlacesApiTest.java
src/test/resources/com/google/maps/PlaceDetailsResponseWithBusinessStatus.json
src/test/resources/com/google/maps/PlacesApiTextSearchResponse.json

Adding business_status as a field to the place details and place search responses. Also added a new field mask for the place details request.

feat: Add business_status

---

src/main/java/com/google/maps/FindPlaceFromTextRequest.java
src/main/java/com/google/maps/PlaceDetailsRequest.java

`permanently_closed` will be replaced by `business_status`.

fix: change permanently_closed to deprecated

---

src/main/java/com/google/maps/PlaceAutocompleteRequest.java
src/main/java/com/google/maps/model/AutocompletePrediction.java
src/test/java/com/google/maps/PlacesApiTest.java

feat: Add distance_meters and origin support for Places Autocomplete

---

.github/workflows/publish.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties

Fixing publish workflow. These are the same modifications made in the
KTX and AMU repos and verified that it is working.
Fixes: #680

build(Publish): Use .gpg key for signing and publishing

---

src/main/java/com/google/maps/DirectionsApi.java
src/main/java/com/google/maps/DirectionsApiRequest.java
src/main/java/com/google/maps/DistanceMatrixApiRequest.java
src/test/java/com/google/maps/DirectionsApiTest.java

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #688 🦕

feat: Add INDOOR enum to RouteRestriction.

---

src/main/java/com/google/maps/DirectionsApi.java

fix: googlemaps#675 Changed return logic of DirectionsApi

---

src/main/java/com/google/maps/errors/ApiException.java

The URL is currently missing in the Check.
---
Fixes #697  🦕

fix : google-maps-services-java#697  missing URL in check for ApiException

---

gradle.properties

Revert since this was never released.

chore: Revert "chore(release): 0.16.0 [skip ci]"

---

.github/workflows/publish.yml
build.gradle
gradle.properties

Now publishing to Maven Central and GitHub packages.

feat: Add GitHub packages as publishable repo

---

build.gradle

chore: Use google-maps-services as artifactId

---

src/main/java/com/google/maps/internal/GaePendingResult.java
src/main/java/com/google/maps/internal/OkHttpPendingResult.java
src/main/java/com/google/maps/model/VehicleType.java

Feat: Add LONG_DISTANCE_TRAIN to VehicleType and fallback to OTHER if unknown value

---

.releaserc

fix: Run release on main.

---

README.md

Add missing semicolon in README
---
Fixes #<issue_number_goes_here> 🦕

docs: Add missing semicolon in README

---

README.md

docs: fix example missing semi-colon and remove defunkt link

---

.github/sync-repo-settings.yaml
.github/workflows/build.yml

chore: rename check to test

---

src/main/java/com/google/maps/GeoApiContext.java

Fix error in javadoc release task.

chore: update javadoc formatting
