- src/main/java/com/google/maps/GeoApiContext.java
This pull request adds support for Proxy configuration.
It just sets the `Proxy` object on the underlying `OkHttpClient` when constructing `GeoApiContext` like so:
```java
GeoApiContext context = new GeoApiContext(new Proxy(Type.HTTP, new InetSocketAddress("host", 8000)));
```
> Adds Proxy support to GeoApiContext

- src/main/java/com/google/maps/model/DirectionsStep.java
In `DirectionStep`, substeps field was named `subSteps` instead of `steps`.
> Fixed direction steps field name

- src/main/java/com/google/maps/model/DirectionsStep.java
- src/main/java/com/google/maps/model/StopDetails.java
- src/main/java/com/google/maps/model/TransitAgency.java
- src/main/java/com/google/maps/model/TransitDetails.java
- src/main/java/com/google/maps/model/TransitLine.java
- src/main/java/com/google/maps/model/Vehicle.java
- src/main/java/com/google/maps/model/VehicleType.java
- src/test/java/com/google/maps/DirectionsApiTest.java
Add transit details based on [documentation](https://developers.google.com/maps/documentation/directions/#TransitDetails).
> Add transit details

- src/main/java/com/google/maps/DirectionsApiRequest.java
- src/main/java/com/google/maps/GeoApiContext.java
- src/main/java/com/google/maps/PendingResultBase.java
- src/main/java/com/google/maps/errors/ApiException.java
- src/main/java/com/google/maps/errors/InvalidRequestException.java
- src/main/java/com/google/maps/errors/MaxElementsExceededException.java
- src/main/java/com/google/maps/errors/NotFoundException.java
- src/main/java/com/google/maps/errors/OverQueryLimitException.java
- src/main/java/com/google/maps/errors/RequestDeniedException.java
- src/main/java/com/google/maps/errors/UnknownErrorException.java
- src/main/java/com/google/maps/errors/ZeroResultsException.java
- src/main/java/com/google/maps/internal/OkHttpPendingResult.java
- src/main/java/com/google/maps/internal/RateLimitExecutorService.java
- src/main/java/com/google/maps/internal/SafeEnumAdapter.java
- src/main/java/com/google/maps/internal/UrlSigner.java
- src/main/java/com/google/maps/model/AddressType.java
I've added some returning but not documented AddressType from https://developers.google.com/places/documentation/supported_types, and optimized the lookup method.
I've made some basic coding style corrections (add serialVersionUID; logger variables be static, etc).
> Added some returning but not documented AddressType.

- src/main/java/com/google/maps/internal/FareAdapter.java
- src/test/java/com/google/maps/DirectionsApiTest.java
* FareAdapter was failing when it hit unknown keys
* A directions API test with transit details was failing due to unexpected test data
> Multiple failed test fixes

- CONTRIBUTORS
- src/main/java/com/google/maps/DistanceMatrixApiRequest.java
- src/main/java/com/google/maps/GeoApiContext.java
- src/main/java/com/google/maps/PendingResultBase.java
Added support for a channel parameter to the GoogleDistanceMatrixRequest (rather than the context), to allow maximum flexibility to callers.
> Added channel parameter to request (issue #77)

- README.md
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/com/google/maps/model/SnappedSpeedLimitResponse.java
- src/test/java/com/google/maps/AuthenticatedTest.java
- src/test/java/com/google/maps/GeocodingApiTest.java
Also trimming whitespace from README.md.
> Making tests happy.

- src/main/java/com/google/maps/DirectionsApiRequest.java
- src/main/java/com/google/maps/model/TrafficModel.java
- src/test/java/com/google/maps/DirectionsApiTest.java
> Added traffic_model parameter to directions requests

- src/main/java/com/google/maps/model/PlacesSearchResult.java
- src/test/java/com/google/maps/PlacesApiIntegrationTest.java
Making sure we can deal with the problematic request detailed in [gmaps-api-issues/9200](https://code.google.com/p/gmaps-api-issues/issues/detail?id=9200).
> Adding tests: UTF8 return parsing and permanently closed

- src/test/java/com/google/maps/DirectionsApiTest.java
- src/test/java/com/google/maps/PlacesApiIntegrationTest.java
> NPE check for route fares, and a better test for permanently closed.

- src/main/java/com/google/maps/model/AddressType.java
- src/main/java/com/google/maps/model/PlacesSearchResult.java
- src/main/java/com/google/maps/model/Vehicle.java
- src/test/java/com/google/maps/DirectionsApiTest.java
- src/test/java/com/google/maps/PlacesApiIntegrationTest.java
- src/test/java/com/google/maps/PlacesApiTest.java
> Bug fixes and cleanups

- src/main/java/com/google/maps/DistanceMatrixApiRequest.java
- src/main/java/com/google/maps/model/DistanceMatrixElement.java
- src/test/java/com/google/maps/DistanceMatrixApiIntegrationTest.java
google returns durationInTraffic in response to distance matrix requests, so adding that to DistanceMatrixElement.  Also adding ability to specify traffic model for distance matrix requests
> distance matrix request - add traffic_model to request and durationInTraffic to response

- src/main/java/com/google/maps/PlaceAutocompleteRequest.java
- src/main/java/com/google/maps/model/PlaceAutocompleteType.java
- src/test/java/com/google/maps/PlacesApiIntegrationTest.java
- src/test/java/com/google/maps/PlacesApiTest.java
Based on my understanding, the autocomplete for places is slightly different than the places search. In particular, it has a parameter name "types" that takes a restricted set of values.
https://developers.google.com/places/web-service/autocomplete
This PR adjusts the autocomplete to reflect this
> Fix places autocomplete types parameter and introduced correct type enum

- src/test/java/com/google/maps/DirectionsApiTest.java
- src/test/java/com/google/maps/DistanceMatrixApiIntegrationTest.java
- src/test/java/com/google/maps/PlacesApiIntegrationTest.java
> Dropping flaky tests.

- src/main/java/com/google/maps/model/AddressComponentType.java
- src/main/java/com/google/maps/model/AddressType.java
- src/test/java/com/google/maps/model/EnumsTest.java
I noticed that while AddressType had the canonical literals (the exact strings in the server response), AddressComponentType didn't have them.
> Adding canonical literals for AddressComponentType

- src/main/java/com/google/maps/model/LatLng.java
See
https://github.com/googlemaps/google-maps-services-java/pull/114#issuecomment-215319159
for context.
> Increasing the precision of LatLng's toUrlValue

- README.md
- build.gradle
- src/main/java/com/google/maps/GaeRequestHandler.java
- src/main/java/com/google/maps/GeoApiContext.java
- src/main/java/com/google/maps/OkHttpRequestHandler.java
- src/main/java/com/google/maps/internal/GaePendingResult.java
- src/test/java/com/google/maps/DistanceMatrixApiTest.java
- src/test/java/com/google/maps/PlacesApiIntegrationTest.java
PTAL @broady @samthor @markmcd 
/cc @lmoroney 
This PR is based on code authored by @ZiglioNZ
> App engine support

- README.md
Moving the client-id example from the developer's guide to GitHub, because it's more relevant closer to the code.
Previous location:
https://developers.google.com/maps/web-services/client-library#usage_java
> Adds client-id example to README.md

- src/test/java/com/google/maps/DirectionsApiTest.java
- src/test/java/com/google/maps/GeocodingApiTest.java
- src/test/java/com/google/maps/PlacesApiIntegrationTest.java
> Cleaning up broken tests

- src/main/java/com/google/maps/internal/RateLimitExecutorService.java
RateLimitExecutorService thread doesn't has a name (oversight?). 
It is not a bug, but it is easer to read stacktraces with thread with names.
> Set RateLimitExecutor thread name.

- src/main/java/com/google/maps/model/PlaceDetails.java
- src/test/java/com/google/maps/PlacesApiTest.java
- src/test/resources/com/google/maps/PlaceDetailsResponseForPermanentlyClosedPlace.json
This attribute is only included in the Places response if the place has shut down. It is not included if the place is still open.
> Add support for the 'permanently_closed' attribute in Place responses.

- src/main/java/com/google/maps/internal/OkHttpPendingResult.java
When the response contents are copied the input stream was not being
closed. This might appear correct for a one-off tests due to new
connections being established. Unfortunately it eventually consumes
the entire pool with stuck connections, resulting in no new requests
being sent. Cancelling the request isn't enough since the connection
is still stuck in a bad state.
The simple solution is to close the InputStream, but since OkHttp has
a method to do this we'll just delete this bad code entirely.
> Fix poor resource management code (fixes #179)

- src/main/java/com/google/maps/model/DirectionsStep.java
The directions API returns a useful element called maneuver which mentions the next action a traveler needs to take. 
This commit adds support to parse that. It was pretty simple since the system does parsing internally based on the field names. I just needed to add the file name.
```
"steps" : [
...
"html_instructions" : "Turn \u003cb\u003eright\u003c/b\u003e onto \u003cb\u003eWightman St\u003c/b\u003e",
"maneuver" : "turn-right",
"polyline" : {
"points" : "w`yuFf{yfNn@?X?X?X?zBClEGxCAj@A~BG"
},
"travel_mode" : "DRIVING"
....
}
```
Thanks,
Pulkit
> Adding support for maneuver in the directions api.

- src/main/java/com/google/maps/GaeRequestHandler.java
- src/main/java/com/google/maps/GeoApiContext.java
- src/main/java/com/google/maps/OkHttpRequestHandler.java
- src/main/java/com/google/maps/internal/GaePendingResult.java
- src/main/java/com/google/maps/internal/OkHttpPendingResult.java
- src/test/java/com/google/maps/GeoApiContextTest.java
In some cases, it can be useful to restrict the number of retries by retry count, not just time. This pull request adds `GeoApiContext.setMaxRetries(Integer)` and `GeoApiContext.disableRetries()`.
This does not remove the ability to limit retries by time.
> Allow retries to be limited by number of retries, not time.

- CONTRIBUTORS
- README.md
- src/main/java/com/google/maps/GaeRequestHandler.java
- src/main/java/com/google/maps/GeoApiContext.java
- src/main/java/com/google/maps/OkHttpRequestHandler.java
- src/main/java/com/google/maps/internal/ExceptionsAllowedToRetry.java
- src/main/java/com/google/maps/internal/GaePendingResult.java
- src/main/java/com/google/maps/internal/OkHttpPendingResult.java
- src/test/java/com/google/maps/GeoApiContextTest.java
- src/test/java/com/google/maps/PlacesApiTest.java
- src/test/java/com/google/maps/TestUtils.java
- src/test/resources/com/google/maps/OverQueryLimitResponse.json
PR #168 hasn't been updated in 2 months so it seems to be abandoned. This PR adds basically the same functionality - but this also allows you to customise which exceptions are retries or not.
By default only `OverQueryLimitException` will be retried. If you don't want to retry after a `OverQueryLimitException` (maybe you are in time-sensitive situation where you want to fail fast), you can disable retries with `toggleifExceptionIsAllowedToRetry(OverQueryLimitException.class, false)`. The same goes for other exception types.
> Allow specific exception types to be retried or not retried

- src/main/java/com/google/maps/DirectionsApi.java
- src/main/java/com/google/maps/DirectionsApiRequest.java
- src/main/java/com/google/maps/model/DirectionsLeg.java
- src/main/java/com/google/maps/model/DirectionsRoute.java
- src/main/java/com/google/maps/model/DirectionsStep.java
- src/main/java/com/google/maps/model/Fare.java
- src/main/java/com/google/maps/model/StopDetails.java
- src/main/java/com/google/maps/model/TransitAgency.java
- src/main/java/com/google/maps/model/TransitLine.java
- src/main/java/com/google/maps/model/TravelMode.java
- src/main/java/com/google/maps/model/Vehicle.java
- src/main/java/com/google/maps/model/VehicleType.java
Links to the Directions API were missing "intro", and therefore were linking to a generic page rather than the specific documentation page.
> Update documentation links that were outdated.

- src/main/java/com/google/maps/DirectionsApiRequest.java
- src/test/java/com/google/maps/DirectionsApiTest.java
The origin and destination methods have two versions, one that takes a String and one that takes a LatLng. This commit adds a second method for the waypoints method that takes in a LatLng array.
> Add waypoints method that takes in an array of LatLng

- CONTRIBUTORS
- src/main/java/com/google/maps/internal/RateLimitExecutorService.java
Instead of using the newWorkStealingPool we can change ThreadPoolExecutor to create as many threads as current available cores. This will allow many threads to execute calls. The problem is that it does not seem to grow/shrink based on the number of operations
> Keep using ThreadPoolExecutor but increase number of threads

- src/main/java/com/google/maps/model/AddressType.java
This value is in `AddressComponentType` but not `AddressType`.
> Add support for address type 'postal_code_prefix'.

- README.md
Documents correct usage of GeoApiContext, since the wrong usage could cause a lot of threads alive in JVM.
> Correct usage of GeoApiContext

- .gitignore
- src/main/java/com/google/maps/internal/UrlSigner.java
- src/test/java/com/google/maps/internal/UrlSignerTest.java
Fixes #254.
I decided to use the clone strategy to maintain compatibility with the current exception handling for `NoSuchAlgorithmException` and `InvalidKeyException` on `UrlSigner` creation.
> Fixing concurrency problem

- src/main/java/com/google/maps/OkHttpRequestHandler.java
- src/main/java/com/google/maps/internal/RateLimitExecutorService.java
Hi.
In this patch, I first adjusted the problem described in issue #256.
But even after this, I did some testing and the parallel performance was still much lower than expected (set in GeoApiContextProvider.setQueryRateLimit)
After a few more tests, I identified that the problem was in the delay between [take operations in RateLimitExecutorService](https://github.com/googlemaps/google-maps-services-java/blob/master/src/main/java/com/google/maps/internal/RateLimitExecutorService.java#L90).
The [ThreadPoolExecutor documentation](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html), explains the overhead of using the LinkedBlockingQueue as workQueue and suggests the use of SynchronousQueue as a good choice.
To my surprise, when I tested only this change I …
> Solving performance problems in parallel processing

- src/main/java/com/google/maps/model/AddressComponentType.java
the gmaps api gave me some interesting additional info about light rail stations, missing from this enum.
> Add light_rail_station enum type

- src/test/java/com/google/maps/GeocodingApiTest.java
Confirming behaviour reported in https://github.com/googlemaps/google-maps-services-java/issues/120 is actually fixed.
> Testing Kita Ward.

- src/main/java/com/google/maps/internal/RateLimitExecutorService.java
Fixes issue where Runnable was running on the RateLimitExecutorDelayThread thread, allowing only one request per rate limit to go through.   This moves it back onto the delegate ExecutorService.  
This looks like it was introduced in Commit 4bf88c29a14214e505765a35bb27ab825472bbaa.
> Fix issue where Runnable runs on the incorrect thread

- src/test/java/com/google/maps/GeocodingApiTest.java
This fixes a missing closing quote in the javadoc in the GeocodingApiTest test. The missing quote is confusing syntax highlighting in Sublime Text for me.
> GeocodingApiTest: fix missing quote in javadoc

- README.md
The documentation publishing instructions look a little out of date. This is a suggestion on fixing them up.
This changes:
* Removes reference to nonexistent `javadoc` directory. Maybe this is a leftover from an older build process?
* Checks out the version tag before building the javadoc, to make sure they're getting exactly that version, and no subsequent changes on master.
* Includes steps to update the `latest` symlink.
* Includes a commit comment that matches the format I saw in the `gh-pages` branch history.
> Update documentation publishing instructions

- .gitignore
- README.md
- src/main/java/com/google/maps/internal/DayOfWeekAdapter.java
- src/main/java/com/google/maps/internal/GaePendingResult.java
- src/main/java/com/google/maps/internal/OkHttpPendingResult.java
- src/main/java/com/google/maps/internal/PriceLevelAdapter.java
This project uses a mix of the spellings "adapter" and "adaptor". I assume that is just a typographical quirk, not an intentional distinction. This PR cleans it up by changing everything to "adapter".
I chose "adapter" over "adaptor" because it's the predominant spelling in this project.
```
[~/local/repos/google-maps-services-java on ⇄ master]
$ grep -ri adapter * | wc -l
182
[~/local/repos/google-maps-services-java on ⇄ master]
$ grep -ri adaptor * | wc -l
7
```
Google n-grams agrees for general usage:
This spelling change includes renaming a couple classes, but they're in the `internal` package, so that shouldn't cause any breakage. (Unless clients are intentionally using `internal` classes, which I assume is unsupported.) 
After this change, the build succeeds and the tests pass for …
> Spell 'adapter' consistently

- .gitignore
This is for users of NetBeans with its Gradle plugin, which drops `.nb-gradle` and `.nb-gradle-properties` as part of its build process. It's a local build file like `.build`, so it shouldn't get checked in to the repo. This change keeps local repos appearing "clean" for NetBeans users, and prevents clutter from accidentally getting checked in.
This also adds a newline at the end of `.gitignore`, which was missing before. That change doesn't matter; it just happened as a side effect of saving the file from `vi` or Sublime Text. Should probably keep it since that's the default behavior for many editors.
> Add .nb-gradle files to .gitignore

- README.md
Maybe the "search" links to Maven Central Repo and Gradle, Please in the README should go to searches for this library, instead of just the home pages?
This PR turns those home page links into links specifically to searches for google-maps-services on those repos. Seems like this would be more convenient for library users.
This PR also picked up some extraneous whitespace-stripping changes due to my Atom editor settings. Sorry about that.
> README: Make central repo links do searches for this lib 

- build.gradle
- src/test/java/com/google/maps/PlacesApiTest.java
When I run `./gradlew test`, there are deprecation warnings because `PlacesApiTest` calls `PlacesApi.radarSearchQuery`, which is deprecated.
When I enable verbose `-Xlint:deprecated`, I get this.
```
> Task :compileTestJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
/Users/janke/local/repos/google-maps-services-java/src/test/java/com/google/maps/GeoApiContextTest.java:79: warning: [unchecked] unchecked method invocation: method get in class GeoApiContext is applied to given types
builder.build().get(new ApiConfig(path), fakeResponse.getClass(), params).awaitIgnoreError();
^
required: ApiConfig,Class<? extends R>,Map<String,String>
found: ApiConfig,Class<CAP#1>,Map<String,String>
where R,T are type-variables:
R extends ApiResponse<T> declared in method …
```
> Suppress deprecation warnings for radarSearchQuery

- build.gradle
- src/test/java/com/google/maps/GeoApiContextTest.java
- src/test/java/com/google/maps/LocalTestServerContext.java
This library uses an old version of `mockwebserver` from back when it was a standalone project. It has since been folded in to OkHttp, which this project also uses. The new `mockwebserver` is at `com.squareup.okhttp3:mockwebserver:3.8.1`.
From their [old Google Code website](https://code.google.com/archive/p/mockwebserver/):
Shall we upgrade to the new version from OkHttp? It looks like this project is keeping current on all its other dependencies.
This PR accomplishes the upgrade by changing the `mockwebserver` dependency to the new `com.squareup.okhttp3:mockwebserver:3.8.1` one, and updating the code to handle the `mockwebserver` API changes between 20130706 and 3.8.1.
Tests pass locally for me.
> Upgrade mockwebserver to 3.8.1 from OkHttp distribution

- src/main/java/com/google/maps/GeoApiContext.java
Fixed GeoApiContext class, because of exception NoClassDefFoundError when using GAE(due of Builder initializing OkHttpRequestHandler). Created another constructor that receives RequestHandler.Builder as workaround.
> Update GeoApiContext.java - Exception using GAE

- build.gradle
com.google.guava:guava v22 require JDK 8, changing to guava v20 makes it compatible with JDK 7+.
> Update build.gradle - Changed guava to v20

- README.md
Updates the "javadoc" link in the README to point at the latest v0.2.1 javadocs.
Depends on https://github.com/googlemaps/google-maps-services-java/pull/310, which actually publishes those v0.2.1 javadocs.
> README: Point "javadoc" link at the new v0.2.1 javadocs

- src/main/java/com/google/maps/model/AddressComponent.java
- src/main/java/com/google/maps/model/AddressComponentType.java
- src/main/java/com/google/maps/model/AddressType.java
- src/main/java/com/google/maps/model/AutocompletePrediction.java
- src/main/java/com/google/maps/model/Bounds.java
- src/main/java/com/google/maps/model/CellTower.java
- src/main/java/com/google/maps/model/ComponentFilter.java
This rephrases several Javadoc elements to [section 7 ("Javadoc")](https://google.github.io/styleguide/javaguide.html#s7-javadoc) of the Google Java Style Guide. In particular, the guide calls for:
> Each Javadoc block begins with a brief summary fragment. This fragment is very important: it is the only part of the text that appears in certain contexts such as class and method indexes.
>
> This is a fragment—a noun phrase or verb phrase, not a complete sentence. It does not begin with A {@code Foo} is a..., or This method returns..., nor does it form a complete imperative sentence like Save the record.. However, the fragment is capitalized and punctuated as if it were a complete sentence.
I've broken this out in to multiple PRs, alphabetically by class name, to make it easier to review, …
> Javadoc: Rephrase to match Google Java Style Guide (classes A-C)

- src/main/java/com/google/maps/DirectionsApi.java
- src/main/java/com/google/maps/ElevationApi.java
- src/main/java/com/google/maps/model/AddressType.java
- src/main/java/com/google/maps/model/AutocompletePrediction.java
- src/main/java/com/google/maps/model/DirectionsLeg.java
- src/main/java/com/google/maps/model/DirectionsResult.java
- src/main/java/com/google/maps/model/DirectionsRoute.java
- src/main/java/com/google/maps/model/DirectionsStep.java
- src/main/java/com/google/maps/model/Distance.java
- src/main/java/com/google/maps/model/DistanceMatrix.java
- src/main/java/com/google/maps/model/DistanceMatrixElement.java
- src/main/java/com/google/maps/model/DistanceMatrixElementStatus.java
- src/main/java/com/google/maps/model/DistanceMatrixRow.java
- src/main/java/com/google/maps/model/Duration.java
- src/main/java/com/google/maps/model/Fare.java
This PR covers classes with names starting with D-F.
> Javadoc: Rephrase to match Google Java Style Guide (classes D-F)

- src/main/java/com/google/maps/DirectionsApi.java
- src/main/java/com/google/maps/model/DistanceMatrixElement.java
- src/main/java/com/google/maps/model/PlaceDetails.java
- src/main/java/com/google/maps/model/TransitDetails.java
Per [@sarahmaddox's comment](https://github.com/googlemaps/google-maps-services-java/issues/312#issuecomment-321104028), prose in this project should use Oxford commas.
I noticed some locations in the Javadoc that were not using Oxford commas. This PR updates those locations to use them.
> Use Oxford commas in Javadoc

- src/main/java/com/google/maps/DirectionsApiRequest.java
- src/main/java/com/google/maps/model/Geometry.java
In this project, when talking about latitude/longitude coordinates, the styling "latitude/longitude" is predominant over "latitude,longitude". (And IMHO, "latitude/longitude" is more conventional English prose.)
```
$ grep -r latitude/longitude * | wc -l
22
$ grep -r latitude,longitude * | wc -l
2
```
This PR changes the remaining "latitude,longitude" instances to be "latitude/longitude".
It also removes the `{@code ...}` markup from one of the instances, because it's not referring to a literal code value or identifiers there.
> Javadoc: Use "latitude/longitude" instead of "latitude,longitude" everywhere

- src/main/java/com/google/maps/NearbySearchRequest.java
- src/main/java/com/google/maps/OkHttpRequestHandler.java
- src/main/java/com/google/maps/errors/OverDailyLimitException.java
- src/main/java/com/google/maps/errors/OverQueryLimitException.java
- src/main/java/com/google/maps/model/LatLng.java
- src/main/java/com/google/maps/model/LocationType.java
- src/main/java/com/google/maps/model/OpeningHours.java
This PR covers classes with names starting with H-O.
> Javadoc: Rephrase to match Google Java Style Guide (classes H-O)

- src/main/java/com/google/maps/model/Vehicle.java
- src/main/java/com/google/maps/model/WifiAccessPoint.java
Also includes minor additions of "code" markup.
This PR covers classes with names starting with U-Z.
> Javadoc: Rephrase to match Google Java Style Guide (classes U-Z)

- src/main/java/com/google/maps/TextSearchRequest.java
- src/main/java/com/google/maps/TimeZoneApi.java
- src/main/java/com/google/maps/model/TransitAgency.java
- src/main/java/com/google/maps/model/TransitDetails.java
- src/main/java/com/google/maps/model/TransitLine.java
- src/main/java/com/google/maps/model/TransitRoutingPreference.java
Also includes minor wording changes, for consistency within classes.
This PR covers classes with names starting with T.
> Javadoc: Rephrase to match Google Java Style Guide (classes T)

- src/main/java/com/google/maps/QueryAutocompleteRequest.java
- src/main/java/com/google/maps/RadarSearchRequest.java
- src/main/java/com/google/maps/model/RankBy.java
- src/main/java/com/google/maps/model/SnappedPoint.java
- src/main/java/com/google/maps/model/SpeedLimit.java
- src/main/java/com/google/maps/model/StopDetails.java
Also includes minor wording and formatting changes.
This PR covers classes with names starting with Q-S.
> Javadoc: Rephrase to match Google Java Style Guide (classes Q-S)

- src/main/java/com/google/maps/GeoApiContext.java
- src/main/java/com/google/maps/GeocodingApi.java
- src/main/java/com/google/maps/GeocodingApiRequest.java
- src/main/java/com/google/maps/GeolocationApiRequest.java
- src/main/java/com/google/maps/model/GeocodedWaypoint.java
- src/main/java/com/google/maps/model/GeocodedWaypointStatus.java
- src/main/java/com/google/maps/model/GeocodingResult.java
- src/main/java/com/google/maps/model/GeolocationPayload.java
- src/main/java/com/google/maps/model/GeolocationResult.java
- src/main/java/com/google/maps/model/Geometry.java
This PR covers classes with names starting with G.
> Javadoc: Rephrase to match Google Java Style Guide (classes G)

- src/main/java/com/google/maps/PendingResult.java
- src/main/java/com/google/maps/PhotoRequest.java
- src/main/java/com/google/maps/PlaceAutocompleteRequest.java
- src/main/java/com/google/maps/PlaceDetailsRequest.java
- src/main/java/com/google/maps/PlacesApi.java
- src/main/java/com/google/maps/model/Photo.java
- src/main/java/com/google/maps/model/PhotoResult.java
- src/main/java/com/google/maps/model/PlaceAutocompleteType.java
- src/main/java/com/google/maps/model/PlaceDetails.java
- src/main/java/com/google/maps/model/PlaceIdScope.java
- src/main/java/com/google/maps/model/PlaceType.java
- src/main/java/com/google/maps/model/PlacesSearchResponse.java
- src/main/java/com/google/maps/model/PlacesSearchResult.java
- src/main/java/com/google/maps/model/PriceLevel.java
This PR covers classes with names starting with P.
> Javadoc: Rephrase to match Google Java Style Guide (classes P)

- build.gradle
https://github.com/google/guava/wiki/Release22
https://github.com/google/guava/wiki/Release23
the guava version is tagged with -android but as has been said many times please don't use google-maps-services-java with android.
> guava v22 and v23 reintroduced java 7 support

- src/main/java/com/google/maps/model/AutcompleteStructuredFormatting.java
- src/main/java/com/google/maps/model/AutocompletePrediction.java
- src/main/java/com/google/maps/model/AutocompleteStructuredFormatting.java
- src/test/java/com/google/maps/PlacesApiTest.java
- src/test/resources/com/google/maps/AutocompletePredictionStructuredFormatting.json
This is a fix for https://github.com/googlemaps/google-maps-services-java/issues/244
> Adding handling for AutocompletePrediction's structured formatting.

- src/main/java/com/google/maps/GaeRequestHandler.java
- src/main/java/com/google/maps/GeoApiContext.java
- src/main/java/com/google/maps/OkHttpRequestHandler.java
its a pull request for issue #336  proxy authentication in GeoApiContext
it can close also the reopened issue #141
> adding proxy authentication in GeoApiContext

- .gitignore
I tried out IntelliJ IDEA with this project and found another variant of gradle-driven build directories which should be ignored by git. Mind adding this in?
This is the build directory used by IntelliJ IDEA with this project, and should
be ignored like /build/ and .nb-gradle/.
> .gitignore: add /out/ to support IntelliJ IDEA

- build.gradle
- src/main/java/com/google/maps/internal/RateLimitExecutorService.java
- src/main/java/com/google/maps/internal/ratelimiter/LongMath.java
- src/main/java/com/google/maps/internal/ratelimiter/Platform.java
- src/main/java/com/google/maps/internal/ratelimiter/Preconditions.java
- src/main/java/com/google/maps/internal/ratelimiter/RateLimiter.java
- src/main/java/com/google/maps/internal/ratelimiter/SmoothRateLimiter.java
- src/main/java/com/google/maps/internal/ratelimiter/Stopwatch.java
- src/main/java/com/google/maps/internal/ratelimiter/Ticker.java
Copies the RateLimiter implementation from Google Guava 23.0 to local classes and drops the Guava dependency. This removes the need for the Guava dependency, which some users feel is heavyweight, and may cause Java 7 compatibility issues. Addresses #285, especially https://github.com/googlemaps/google-maps-services-java/issues/285#issuecomment-322363984.
This PR replaces the Guava dependency with a local copy of a minimal set of Guava classes/methods needed to implement RateLimiter, all under the new com.google.maps.internal.ratelimiter package. Code was copied from Guava 23.0 and hand-modified as necessary to get it running under Java 7 and without Guava-supplied annotations.
Doing a mechanical repackaging of RateLimiter and its dependencies would have been quite large (187 classes in …
> Replace Guava dep with local RateLimiter implementation copy-paste

- src/main/java/com/google/maps/GeolocationApi.java
- src/main/java/com/google/maps/OkHttpRequestHandler.java
- src/main/java/com/google/maps/internal/GeolocationResponseAdapter.java
- src/test/java/com/google/maps/DirectionsApiTest.java
- src/test/java/com/google/maps/DistanceMatrixApiTest.java
- src/test/java/com/google/maps/PlacesApiTest.java
- src/test/java/com/google/maps/RoadsApiIntegrationTest.java
- src/test/java/com/google/maps/TestUtils.java
- src/test/java/com/google/maps/TimeZoneApiTest.java
Remediating unused logger declarations, variables, and unclosed Closeables.
> Tidying up warnings.

- src/main/java/com/google/maps/GaeRequestHandler.java
- src/main/java/com/google/maps/GeoApiContext.java
- src/main/java/com/google/maps/OkHttpRequestHandler.java
- src/main/java/com/google/maps/internal/RateLimitExecutorService.java
- src/test/java/com/google/maps/GeoApiContextTest.java
- src/test/java/com/google/maps/TestUtils.java
- src/test/java/com/google/maps/internal/RateLimitExecutorServiceTest.java
This is a pull request for issue #261. Details can be found in the [comment](https://github.com/googlemaps/google-maps-services-java/issues/261#issuecomment-341965630) but I will also copy them here for convenience.
The root cause of the issue is following. We are creating and starting a thread in a constructor of class [RateLimitExecutorService](https://github.com/googlemaps/google-maps-services-java/blob/7d7f0b998a734acc7f32ffb4760e84c1d288e4bb/src/main/java/com/google/maps/internal/RateLimitExecutorService.java#L36). Here it is:
```java
public RateLimitExecutorService() {
setQueriesPerSecond(DEFAULT_QUERIES_PER_SECOND);
Thread delayThread = new Thread(this);
delayThread.setDaemon(true);
delayThread.setName("RateLimitExecutorDelayThread");
delayThread.start();
}
``` …
> added a shutdown method to GeoApiContext which stops RateLimitExecutorDelayThread #261

- src/main/java/com/google/maps/internal/OkHttpPendingResult.java
Was getting the following warning without this change:
Nov 08, 2017 2:55:28 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://maps.googleapis.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
> ResponseBody in OkHttpPendingResult was not being closed.

- src/test/java/com/google/maps/GeoApiContextTest.java
What do you think about suppressing this unchecked-conversion warning in the GeoApiContextTest? Since it's just in a test using mock objects, I think that'd be acceptable.
When compiling now, I get this "note" output from the test compilation step.
```
> Task :compileTestJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: /Users/janke/local/repos/google-maps-services-java/src/test/java/com/google/maps/GeoApiContextTest.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```
With `-Xlint:unchecked` on:
```
> Task :compileTestJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
/Users/janke/local/repos/google-maps-services-java/src/test/java/com/google/maps/GeoApiContextTest.java:8 …
```
> Suppress unchecked warning in GeoApiContextTest

- .gitignore
This PR pulls in all the new items in `.gitignore` on `master`, so IDE droppings and the like are still ignored when switching between the branches.
> Sync up .gitignore with master

- src/main/java/com/google/maps/model/AddressType.java
Fixes #279. (At least the original report, not the additional items noted in comments.)
> AddressType: add CASINO and PARKING

- src/main/java/com/google/maps/model/AddressType.java
Fixes #279 (from comment https://github.com/googlemaps/google-maps-services-java/issues/279#issuecomment-339551783).
I can reproduce that comment's warnings locally, and this patch fixes them.
> AddressType: add beauty care types

- src/main/java/com/google/maps/model/AddressType.java
Fixes #226 (comment https://github.com/googlemaps/google-maps-services-java/issues/226#issuecomment-340790353)
This PR includes the `SUPERMARKET` type because even though it's not listed in the [official web page](https://developers.google.com/places/supported_types) as of this writing, @steveetl reports seeing it in the wild.
> AddressType: add more types observed by steveetl

- src/main/java/com/google/maps/model/AddressType.java
This PR adds the `shoe_store` `AddressType`.
Before: Produces warning:
```
$ ./bin/gmsj-cli geocode "bucket shoe store"
[main] WARN com.google.maps.internal.SafeEnumAdapter - Unknown type for enum com.google.maps.model.AddressType: 'shoe_store'
Results length: 1
Result 0:
Formatted Address: 1924 8th St NW, Washington, DC 20001, USA
Types: establishment / point_of_interest / unknown / store
PlaceId: ChIJ8cLMP-W3t4kRHrH3_aZWIx0
```
After: No warning:
```
$ ./bin/gmsj-cli geocode "bucket shoe store"
Results length: 1
Result 0:
Formatted Address: 1924 8th St NW, Washington, DC 20001, USA
Types: establishment / point_of_interest / shoe_store / store
PlaceId: ChIJ8cLMP-W3t4kRHrH3_aZWIx0
```
> AddressType: add shoe_store

- src/main/java/com/google/maps/model/AddressType.java
This PR adds the `travel_agency` AddressType.
Before:
```
$ ./bin/gmsj-cli geocode "wherever"
[main] WARN com.google.maps.internal.SafeEnumAdapter - Unknown type for enum com.google.maps.model.AddressType: 'travel_agency'
Results length: 1
Result 0:
Formatted Address: 440 S Main St, Milltown, NJ 08850, USA
[...]
```
After:
```
$ ./bin/gmsj-cli geocode "wherever"
Results length: 1
Result 0:
Formatted Address: 440 S Main St, Milltown, NJ 08850, USA
Types: establishment / point_of_interest / travel_agency
[...]
```
> AddressType: add travel_agency

- src/main/java/com/google/maps/model/AddressType.java
This PR adds the `NIGHT_CLUB` `AddressType`.
Before:
```
$ ./bin/gmsj-cli geocode "BFE"
[main] WARN com.google.maps.internal.SafeEnumAdapter - Unknown type for enum com.google.maps.model.AddressType: 'night_club'
Results length: 1
Result 0:
Formatted Address: 11528 Jones Rd, Houston, TX 77070, USA
Types: establishment / unknown / point_of_interest
```
After:
```
$ ./bin/gmsj-cli geocode "BFE"
Results length: 1
Result 0:
Formatted Address: 11528 Jones Rd, Houston, TX 77070, USA
Types: establishment / night_club / point_of_interest
```
> AddressType: add night_club

- src/main/java/com/google/maps/DirectionsApiRequest.java
Rather than making the DirectionApiRequest.java as singleton class, we need to give its constructor the public access.
> Made the constructor public

- src/main/java/com/google/maps/DirectionsApiRequest.java
Reverts googlemaps/google-maps-services-java#394
Original change https://github.com/googlemaps/google-maps-services-java/pull/393
Reintroducing now that @Sameer9 has now signed the CLA.
> Revert "Revert "Made the constructor public""

- src/main/java/com/google/maps/model/AddressType.java
Added museum type after received this error:
```
WARN - com.google.maps.internal.SafeEnumAdapter : Unknown type for enum com.google.maps.model.AddressType: 'museum'
```
> added museum to address type

- src/main/java/com/google/maps/model/AddressType.java
Added missing enums fields.
```
WARN - com.google.maps.internal.SafeEnumAdapter : Unknown type for enum com.google.maps.model.AddressType:  ...
```
Types observed:
city_hall
atm
bank
local_government_office
> Added missing enums fields

- src/main/java/com/google/maps/internal/OkHttpPendingResult.java
This fixes the issue reported in https://github.com/googlemaps/google-maps-services-java/issues/179
> close response on retry

- src/main/java/com/google/maps/StaticMapsRequest.java
- src/test/java/com/google/maps/StaticMapsApiTest.java
It appears that Google supports a `scale` parameter for custom marker icons although this is undocumented. See the Stack Overflow articles below. This is ultimately necessary when generating maps for hi-DPI screens where the overall map `scale` option is set to 2 or 4. I've tested with this locally and it appears to be working albeit it is undocumented by Google.
https://stackoverflow.com/questions/8813143/how-do-i-add-a-high-resolution-custom-marker-on-a-static-google-map
https://stackoverflow.com/questions/10336646/how-can-i-use-high-resolution-custom-markers-with-the-scale-parameter-in-google
> Add support for scale parameter on custom icons to be able to use hi-DPI icons when map scale > 1

- src/main/java/com/google/maps/model/AddressComponentType.java
- src/main/java/com/google/maps/model/AddressType.java
- src/test/java/com/google/maps/model/EnumsTest.java
This PR adds more currently-unrecognized AddressComponentTypes and AddressTypes.
AddressTypes:
* general_contractor
AddressComponentTypes:
* travel_agency
* electronics_store
* home_goods_store
* school
* store
* art_gallery
* lawyer
* restaurant
* bar
* meal_takeaway
* clothing_store
* local_government_office
* finance
* moving_company
* storage
These were discovered using my [gmsj-cli](https://github.com/apjanke/gmsj-cli) fuzz tester.
```
$ ./bin/gmsj-cli geofuzz "555 Broadway, New York, NY" -n 5000 -S 123456                                                                                           master
Searching 5000 points around '555 Broadway, New York, NY', with radius 0.100000 degrees (rand seed 123456)
[main] WARN com.google.maps.internal.SafeEnumAdapter - Unknown type for enum …
```
> Add more AddressTypes and AddressComponentTypes

- src/main/java/com/google/maps/GaeRequestHandler.java
- src/main/java/com/google/maps/GeolocationApiRequest.java
- src/main/java/com/google/maps/OkHttpRequestHandler.java
- src/main/java/com/google/maps/StaticMapsRequest.java
- src/main/java/com/google/maps/internal/GaePendingResult.java
- src/main/java/com/google/maps/internal/OkHttpPendingResult.java
- src/main/java/com/google/maps/internal/PolylineEncoding.java
- src/main/java/com/google/maps/internal/RateLimitExecutorService.java
- src/main/java/com/google/maps/internal/ratelimiter/RateLimiter.java
- src/main/java/com/google/maps/model/CellTower.java
- src/main/java/com/google/maps/model/GeolocationPayload.java
- src/main/java/com/google/maps/model/WifiAccessPoint.java
- src/test/java/com/google/maps/DirectionsApiTest.java
- src/test/java/com/google/maps/GeocodingApiTest.java
- src/test/java/com/google/maps/PlacesApiTest.java
- src/test/java/com/google/maps/internal/RateLimitExecutorServiceTest.java
- src/test/java/com/google/maps/model/EnumsTest.java
This PR contains some suggestions for minor code hygiene changes. No behavior changes; just refactoring, mostly to use newer post-Java-1.5 stuff.
* Removes unnecessary explicit primitive value boxing
* Uses the diamond operator for parameterized type inference where possible
* Removes redundant `static` and `final` modifiers
* Removes a couple unnecessary pieces of syntax
This PR is split up into separate commits for each type of change, to make review easier.
> Minor code hygiene suggestions

- src/main/java/com/google/maps/internal/PolylineEncoding.java
As far as I know, `@url` is not a standard Javadoc tag type, and I don't see a custom tag definition for it in this project.
This PR replaces a use of `@url` with a regular HTML link. It's in an `internal` class, so it won't show up in the generated Javadoc and doesn't actually matter, but it gets rid of a warning in static inspection tools that validate Javadoc.
> Replace bogus @url Javadoc tag with HTML link

- src/main/java/com/google/maps/model/PlaceDetails.java
- src/test/java/com/google/maps/PlacesApiTest.java
Fixes #434.
The Place Details API doc says the values in `types` are valid address types, so we can, and probably should, represent them as AddressTypes.
> PlaceDetails: make types an AddressType[] instead of String[]

- src/main/java/com/google/maps/NearbySearchRequest.java
Fixes #430.
Per the [Place Search Request doco](https://developers.google.com/places/web-service/search#PlaceSearchRequests), `type` arguments after the first are silently ignored.
> Deprecate NearbySearchRequest.type(PlaceType...)

- src/main/java/com/google/maps/OkHttpRequestHandler.java
This is a minor optimization to support clients that are "doing the wrong thing" and creating many GeoApiContext objects. It somewhat reduces thread and memory pressure in that situation, and makes applications easier to monitor in tools like VisualVM.
Without this patch, in my testing, OkHttpWorker threads accumulate up to about 800 threads before leveling off, with several threads appearing per new GeoApiContext object. With this patch, the growth is slower, and steady state levels off at about 300 threads.
This is not a critical fix; just a nicety for some users.
Follows up discussion in #261.
> Have OkHttpRequestHandler evict connectionPool on shutdown

- src/main/java/com/google/maps/GeoApiContext.java
Adds a note to the GeoApiContext Javadoc encouraging users to reuse their objects. Should make it more clear that this is intended for Singleton-style use.
> Add note on GeoApiContext reuse in Javadoc

- src/main/java/com/google/maps/model/GeocodingResult.java
- src/main/java/com/google/maps/model/PlaceDetails.java
- src/main/java/com/google/maps/model/PlusCode.java
- src/test/resources/com/google/maps/PlaceDetailsLookupGoogleSydneyResponse.json
Fixes #458.
I've added test data for the PlaceDetails support, but not for the GeocodingResult, because I'm not able to see `plus_code` in my Geocoding queries yet, probably due to a staged rollout of the Plus Code feature. This PR adds forward-compatible support for clients who can see it, though.
> Add Plus Code support to GeocodingResult and PlaceDetails

- src/main/java/com/google/maps/model/DirectionsStep.java
- src/test/java/com/google/maps/DirectionsApiTest.java
There's a NullPointerException in the DirectionsStep.toString() introduced in https://github.com/googlemaps/google-maps-services-java/commit/0a2986a6bc64b0666e298fe6ca95caee792c5269. It assumes the substeps array is non-null. This fixes it.
Discovered in testing https://github.com/apjanke/gmsj-cli/commit/0e5183213575fc1a1929f3f11f05fea3dc5fa578.
Regression test included.
Sorry!
> Fix an NPE in DirectionsStep.toString()

- build.gradle
Per the [Gradle 4.8.1 documentation](https://docs.gradle.org/4.8.1/userguide/java_plugin.html), the 'compile' and 'testCompile' keywords are deprecated. 
This PR updates `build.gradle` to use the current non-deprecated alternatives.
This might be a breaking change for client code that is building with Gradle or Maven and relying on google-maps-services-java to provide transitive dependencies for these libraries. I think that's acceptable, though, because they "shouldn't be" doing that, and the fix is easy: just add the dependencies to their own `build.gradle` file.
> Update gradle dependency keywords

- build.gradle
Fixes #467
This PR supplies an explicit `-html4` to `javadoc` when running under JDK 10 and later. Otherwise, they complain about the Javadoc HTML version not being explicitly specified.
> Supply -html4 to javadoc with JDK 10 and later

- src/main/java/com/google/maps/GaeRequestHandler.java
- src/main/java/com/google/maps/GeoApiContext.java
- src/main/java/com/google/maps/OkHttpRequestHandler.java
Most Builder Pattern objects have their setters return `this` so calls are chainable. GeoApiContext.RequestHandler.Builder and its concrete implementations do not do this; they return `void` instead.
This seems like just an oversight to me; I don't see a technical reason for them not to be chainable.
This PR changes GeoApiContext.RequestHandler.Builder and its concrete subclasses to return `this` from its setter methods, so calls on them are chainable.
> Change *RequestHandler Builder signatures to do chainable calls

- src/main/java/com/google/maps/DirectionsApiRequest.java
- src/test/java/com/google/maps/DirectionsApiTest.java
This PR adds support for non-stopover waypoints.
Fixes #93.
NOTE: This PR also slightly changes the current behavior of the `waypoints(...)` methods. Previously, when `waypoints(...)` was called with a `null` or empty array argument, it was simply ignored. That means that if `waypoints(...)` had previously been called, the effect of the previous value was simply kept. I think that's the wrong behavior: for empty array arguments, and I think for null arguments too if we allow those, I think calling `waypoints([])` or waypoints(null)` should instead reset the waypoints parameter to the empty set. This PR changes the behavior to do so.
This PR also fixes a typo in the function name of one of the tests in DirectionsApiTest.
> Add non-stopover waypoint support

- src/main/java/com/google/maps/model/PlaceDetails.java
Fixes #479.
I did not include `adrAddress` in the toString output because it's pretty long and noisy IMHO, repeating other information already in toString().
> PlaceDetails: add adr_address support

- src/main/java/com/google/maps/GeoApiContext.java
- src/test/java/com/google/maps/LocalTestServerContext.java
Fixes #435.
The name `baseUrlForTesting` implies a certain use case, but the action is really a general override of the base URL. Turns out it's useful in other scenarios, such as querying Google Maps from China, as stated in #435.
This PR replaces `baseUrlForTesting(...)` with a new usage-neutral-terminology `baseUrlOverride(...)` that describes what it does, but not why. The old `baseUrlForTesting(...)` is left around in a `@Deprecated` state for now.
> Replace "baseUrlForTesting()" with usage-neutral "baseUrlOverride()"

- src/main/java/com/google/maps/PlaceDetailsRequest.java
According to the official docs, the field should be called "review", not "reviews". It appears that "reviews" also work, but the correct term is "review". More info in the doc:
https://developers.google.com/places/web-service/details#fields
> Fixed typo in field

- src/main/java/com/google/maps/StaticMapsRequest.java
- src/test/java/com/google/maps/StaticMapsApiTest.java
Closes #233.
This adds a `StaticMapsRequest.path(path)` variant that accepts an `EncodedPolyline` as the `path` argument. It uses the encoded polyline in the request it produces.
The test case EncodedPolyline was produced using https://github.com/apjanke/gmsj-cli/commit/599cee7e09b9824c61e03223de570d27e3eb1e5e. It seems to produce a correctly formatted request. I have not tested it by actually running the requests against the Google Maps API server, though.
> Add StaticMapsRequest.path(EncodedPolyline)

- src/main/java/com/google/maps/internal/GaePendingResult.java
- src/main/java/com/google/maps/internal/OkHttpPendingResult.java
- src/main/java/com/google/maps/internal/ZonedDateTimeAdapter.java
- src/main/java/com/google/maps/model/DirectionsLeg.java
- src/main/java/com/google/maps/model/TransitDetails.java
This preserves the time zone information from the API response data.
This is a breaking change to the public API! Per the discussion at https://github.com/googlemaps/google-maps-services-java/issues/514#issuecomment-441160366, this should be okay.
> DirectionsLeg, TransitDetails: use ZonedDateTime instead of LocalDateTime

- build.gradle
The jacoco Gradle plugin seems to be defaulting to Jacoco 0.8.1, which breaks when run against OpenJDK 11. This PR adds an explicit version to force it to use 0.8.2.
JDK 11 support was added recently and picked up in Jacoco 0.8.2: https://github.com/jacoco/jacoco/issues/663
This fixes test errors as seen in https://github.com/googlemaps/google-maps-services-java/pull/513#issuecomment-439308531, which look like the following.
```
FATAL ERROR in native method: processing of -javaagent failed
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
at java.base/java.lang.Class.getField(Class.java:2000)
at org.jacoco.agent.rt.internal_c13123e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)
... 9 more
Process 'Gradle Test Executor 9' finished with …
```
> Force Jacoco version 0.8.2 for OpenJDK 11 compatibility

- src/main/java/com/google/maps/DirectionsApiRequest.java
Place IDs can be provided as origin, destination and waypoints. But in order to be used, they must be prefixed with `place_id:`.
I took the liberty of implementing this, so I added new methods for setting an origin and a destination as a Place ID, as well as a method to set waypoints based on Place IDs, There's a new helper method for prefixing Place IDs, which could be used to pass Place IDs waypoints into the waypoints method that accepts Strings, alongside addresses. This way users can mix addresses and Place IDs if they want to.
> Added support to Place IDs

- gradle/wrapper/gradle-wrapper.properties
:signArchives fails with duplicate key.
> Reverting Gradle version.

- src/main/java/com/google/maps/model/AddressComponentType.java
- src/main/java/com/google/maps/model/AddressType.java
- src/test/java/com/google/maps/model/EnumsTest.java
> Add new address and address component types

- src/main/java/com/google/maps/model/AddressComponentType.java
- src/test/java/com/google/maps/model/EnumsTest.java
I saw the following error from google-maps-services this morning:
`Unknown type for enum com.google.maps.model.AddressComponentType: 'meal_delivery'`
So I thought I'd take the initiative and add it as a new `AddressComponentType`.
> Add meal_delivery AddressComponentType

- src/main/java/com/google/maps/model/PlaceType.java
I found out that `light_rail_station` is supported as PlaceType. However, it's not [documented](https://developers.google.com/places/web-service/supported_types), so I'm not sure about this, WDYT?
> Add Light Rail Station into PlaceType

- CONTRIBUTORS
- src/main/java/com/google/maps/TextSearchRequest.java
Updated logic in `validateRequest` method of `TextSearchRequest` class
Fixes #564
> Validate TextSearchRequest without query if type is set

- src/main/java/com/google/maps/PlacesApi.java
- src/test/java/com/google/maps/PlacesApiTest.java
This PR implements my suggestion in #566 
Adds new overload to `PlacesApi.textSearchQuery` method for cases where the user wants to pass a `type` but no `query`. This is allowable according to the [docs](https://developers.google.com/places/web-service/search#TextSearchRequests) and tests pass.
> [NOT URGENT] add new textSearchQuery (overload) method with test

- src/main/java/com/google/maps/model/PlacesSearchResult.java
- src/test/java/com/google/maps/PlacesApiTest.java
Hello 👋 
Currently, I am working on the project that requires extended usage of google maps API. I want to contribute and add the missing field that we find useful in our service (Seems like other people too - see issue #560 ). 
I tried to follow the conventions and also added the test case for that. 
Thanks!
> Add user_ratings_total to the PlaceSearchResult

- src/main/java/com/google/maps/TextSearchRequest.java
- src/main/java/com/google/maps/model/PlacesSearchResult.java
- src/test/java/com/google/maps/PlacesApiTest.java
Fixes the broken Travis tests by ensuring `./gradlew check` passes.
```
./gradlew check
> Task :test
objc[56081]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java (0x10ccbf4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10cd434e0). One of the two will be used. Which one is undefined.
> Task :verifyGoogleJavaFormat FAILED
The following files are not formatted properly:
/Users/timmerman/Documents/github/grant/google-maps-services-java/src/test/java/com/google/maps/PlacesApiTest.java
/Users/timmerman/Documents/github/grant/google-maps-services-java/src/main/java/com/google/maps/TextSearchRequest.java
/Users/timmerman/Documents/github/grant/google-maps-services-java/s …
```
> Fix: Format java files that break tests using gradlew check

- src/main/java/com/google/maps/PlaceDetailsRequest.java
Without it you can't request a subset of fields in a details request that includes `plus_code`.
> Include plus_code in PlaceDetailsRequest.FieldMask

- CHANGELOG.md
- src/main/java/com/google/maps/PlaceDetailsRequest.java
- src/main/java/com/google/maps/model/PlaceIdScope.java
- src/main/java/com/google/maps/model/PlacesSearchResult.java
- src/test/java/com/google/maps/PlacesApiTest.java
Place fields, `alt_id`, `id`, `reference`, and `scope`, are now deprecated. This annotates these objects as such. Read more about this at https://developers.google.com/maps/deprecations.
closes #604
> deprecation warning for place fields: `alt_id`, `id`, `reference`, and `scope`

- README.md
closes #609 with the simplest solution
> direct users to javadoc.io instead of github pages

- src/main/java/com/google/maps/model/PlaceDetails.java
this should have been included in #605
> mark additional deprecations for alt_id and scope in PlaceDetails

- src/main/java/com/google/maps/model/AddressComponentType.java
- src/test/java/com/google/maps/model/EnumsTest.java
I'm using v0.10.0 and I've seen occurrences of the following AddressComponentTypes. This will conflict with #629  unfortunately, I can fix any conflicts if that is merged first.
> Add more AddressComponentTypes

- README.md
in the readme file, the call of the shutdown () method is not specified at the end of a request.
this is a problem because after n requests java creates multiple threads not closed
and in the case of tomcat the instance goes into error
> documentation problem

- src/main/java/com/google/maps/StaticMapsRequest.java
- src/test/java/com/google/maps/StaticMapsApiTest.java
We saw in the documentation (https://developers.google.com/maps/documentation/maps-static/dev-guide?hl=es#ImplicitPositioning ) these lines:
"Normally, you need to specify center and zoom URL parameters to define the location and zoom level of your generated map. However, if you supply markers, path, or visible parameters, you can instead let the Maps Static API determine the correct center and zoom level implicitly, based on evaluation of the position of these elements."
> fixed: Added path exception when there is no center or no zoom

- src/main/java/com/google/maps/errors/MaxRouteLengthExceededException.java
The original documentation appears to have been copied from `MaxElementsExceededException`.
> Fix `MaxRouteLengthExceededException` documentation

- src/main/java/com/google/maps/PlaceDetailsRequest.java
This is a fix for field `GEOMETRY_LOCATION_LNG` from `FieldMask` enum. Google Place API was unable to recognize `lon`. After changing to `lng` it works fine.
> Typo in FieldMask fixed

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- Upgrading Gradle wrapper to 6.1.1
- Adding `withJavadocJar` & `withJavadocJar` to ensure that javadoc + sources .jar are published when running `./gradlew publish`
I verified that this works when manually running `./gradlew publish`. Still need to verify that this works with the deploy script that travis executes (we can verify this on the next release)
> build(Gradle): upgrade gradle wrapper to 6.1.1

- src/main/java/com/google/maps/GaeRequestHandler.java
- src/main/java/com/google/maps/GeoApiContext.java
- src/main/java/com/google/maps/OkHttpRequestHandler.java
- src/main/java/com/google/maps/internal/GaePendingResult.java
- src/main/java/com/google/maps/internal/OkHttpPendingResult.java
- src/main/java/com/google/maps/metrics/NoOpRequestMetrics.java
- src/main/java/com/google/maps/metrics/NoOpRequestMetricsReporter.java
- src/main/java/com/google/maps/metrics/RequestMetrics.java
- src/main/java/com/google/maps/metrics/RequestMetricsReporter.java
Create hooks for detecting request timing and errors, as well as retries and network timing.
Add a default no-op handler that will not do anything.
This is setting up the interfaces for #663 🦕
> feat: Add hooks for performance logging

- build.gradle
- src/main/java/com/google/maps/metrics/OpenCensusMetrics.java
- src/main/java/com/google/maps/metrics/OpenCensusRequestMetrics.java
- src/main/java/com/google/maps/metrics/OpenCensusRequestMetricsReporter.java
- src/test/java/com/google/maps/metrics/OpenCensusTest.java
This is an OpenCensus implementation for RequestMetrics added in #664.
By default it OpenCensus will not log to any target destination.
This is providing a useful implementation for #663 🦕
> feat: Add OpenCensus implementation for performance logging

- .github/workflows/publish.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Using in-memory ascii-armored key for signing when publishing a build. Also bump gradle to 6.3.
> build: Use in-memory ascii-armored keys for signing.

- src/main/java/com/google/maps/model/AddressType.java
- src/test/java/com/google/maps/model/EnumsTest.java
Fixes #700  🦕
Example of warning:
```
Unknown type for enum com.google.maps.model.AddressType: 'plus_code'
```
Example of a query with `plus_code` address type:
https://maps.googleapis.com/maps/api/geocode/json?address=393V%2BP9%20Ten-Bel%2C%20Spain
> fix: Added `plus_code` address type to fix `SafeEnumAdapter` warnings

- src/main/java/com/google/maps/GeoApiContext.java
closeable implemented to have standard java API to free up resource
Fixes #701  🦕
> fix: #701 Added Closeable interface to GeoApiContext

- src/main/java/com/google/maps/errors/ApiException.java
> fix: googlemaps#697 Changed expected error message in to ApiException

- build.gradle
See https://github.com/google/gson/compare/gson-parent-2.8.5...gson-parent-2.8.6
---
This causes [dependency convergence](https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html) in downstream code since 2.8.5 is a very old version.
> chore(deps): Upgrade Gson 2.8.5 -> 2.8.6

- .gitignore
- src/main/java/com/google/maps/model/AddressType.java
- src/test/java/com/google/maps/model/EnumsTest.java
Revert PR #698 since PLUS_CODE was already defined and introduced in bb4e1ad5.
> chore: Revert "feat: Add AddressType.PLUS_CODE (#698)"

- .github/workflows/publish.yml
Looks like the secret key was incorrectly named which was likely why publishing 401s. This should fix #695
> fix: Fix incorrect secret key for publishing

- .github/workflows/publish.yml
Publish workflow was still failing after #716. Escaping the password however fixed #695. 
After these changes, I verified that the publish workflow works now. See: https://github.com/googlemaps/google-maps-services-java/actions/runs/529636053
> fix: Escape sonatype password

- src/main/java/com/google/maps/PlaceAutocompleteRequest.java
> fix: allow using existing session token(String) in place autocomplete

- .releaserc
- build.gradle
- gradle.properties
Moving version to build.gradle file instead of gradle.properties
> chore: Move version to build.gradle file.

- build.gradle
Bump okhttp to 4.9.1 which is the latest version as of writing.
Related: https://publicobject.com/2020/02/25/okhttp-restricted-apis/
Fixes #735 🦕
> fix: Bump okhttp dependency to 4.9.1

- README.md
Clarify in snippet that `shutdown()` must be invoked when a `GeoApiContext` is no longer used.
Relates to #261
> docs: Make GeoApiContext shutdown() more prominent in code snippet.

- src/main/java/com/google/maps/GaeRequestHandler.java
- src/main/java/com/google/maps/GeoApiContext.java
- src/main/java/com/google/maps/OkHttpRequestHandler.java
- src/main/java/com/google/maps/PendingResultBase.java
- src/main/java/com/google/maps/internal/HttpHeaders.java
- src/test/java/com/google/maps/GeoApiContextTest.java
- src/test/java/com/google/maps/GeocodingApiTest.java
- src/test/java/com/google/maps/LocalTestServerContext.java
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #743 🦕
> feat!: Support setting experienceIds on a per request basis.

- src/main/java/com/google/maps/NearestRoadsApiRequest.java
- src/main/java/com/google/maps/RoadsApi.java
- src/main/java/com/google/maps/SnapToRoadsApiRequest.java
- src/main/java/com/google/maps/SpeedLimitsApiRequest.java
- src/main/java/com/google/maps/model/SnappedSpeedLimitResult.java
- src/test/java/com/google/maps/RoadsApiIntegrationTest.java
Created `SpeedLimitsApiResponse`, `SnapToRoadsApiRequest` and `NearestRoadsApiRequest`
of type `PendingResultBase`.
BREAKING CHANGE: request signature in RoadsApi has changed to account for these new classes.
Previous usage of RoadsApi:
```
PendingResult<SnappedPoint[]> pendingResult = RoadsApi.snapToRoads(context, path);
SnappedPoints[] points = pendingResult.await();
```
New usage:
```
SnapToRoadsApiRequest request = RoadsApi.snapToRoads(context, path);
// Optional request modification
request.header("HEADER_KEY", "HEADER_VAL");
SnappedPoints[] points = request.await();
```
Fixes #788 🦕
> feat!: Create PendingResultBase type requests for Roads API.

- build.gradle
Fix for https://github.com/googlemaps/google-maps-services-java/issues/816
> fix: upgrades okhttp3 to 5.0.0-alpha.7

- src/main/java/com/google/maps/GeoApiContext.java
Makes baseUrlOverride public to allow projects to create a local test context similar to LocalTestServerContext.
Fixes #805  🦕
> feat: make baseUrlOverride() public

- build.gradle
This change partially reverts the upgrade performed in #829, and is an alternative fix for #816. OkHttp 4.10.0 depends on Kotlin 1.6.20, which is not vulnerable to CVE-2020-29582.
This downgrade also resolves #832.
See:
- https://square.github.io/okhttp/changelogs/changelog_4x/#version-4100
- https://nvd.nist.gov/vuln/detail/CVE-2020-29582
> fix: Downgrade OkHttp 5.0.0-alpha.7 -> 4.10.0

- src/main/java/com/google/maps/PlaceDetailsRequest.java
wrong param names in reviewsSort and reviewsNoTranslations
> fix: javadoc in PlaceDetailsRequest
